### ISSUE TITLE
2.7.0.0 Still has issues with the last windows user

### ISSUE THREAD

**Issue by bigben386** [OCSInventory-NG/WindowsAgent#168]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  windows 10

### OCS Inventory information
Windows agent version :  2.7.0.0

### Problem's description
*Describe your problem here*: Many windows PC show blank last connected users. This has been going on since agent 2.4.0. We need the agent to stop updating the last connected user if it is not detecting one instead of setting a blank username.

### Inventory log file ( optional )
*Use github cloud or trusted upload website*
[OCSInventory.log](https://github.com/OCSInventory-NG/WindowsAgent/files/4805335/OCSInventory.log)

**Comment by gillesdubois** [comment]
Hi,

I understand the problem, however our agent retrieve the informations at the time of inventory.
If no session is active, the connected user will be empty. I don't know from where you saw "Last connected" (check the screen below) since we are only retrieving the connected user at the time of the inventory.

![image](https://user-images.githubusercontent.com/9396603/85151233-d5f73880-b253-11ea-9c48-f475c680d6d0.png)

If you want more informations on winusers, we have a dedicated plugin. If this feature is not fitting your needs or not available you can submit a feature request. In the case you don't want to wait, we still have a professional service.

Regards,
Gilles Dubois.

**Comment by bigben386** [comment]
Why do we need a feature request for something that used to work pre 2.4.0 agent? Why don't you just not update the user on the server if the current user is not detectable?

**Comment by gillesdubois** [comment]
The user retrieval has been reworked with the 2.4.0.0 to have a better and more accurate reporting.

When doing that change we decided to not perform any post-processing on the information and send it "as it is".

In your case, it seem that having the "Connected User" as the "Last Connected User" is a plus. It's also a plus for most of the people who use GLPI because of the way the connector is working.
However, we interconnect with other product that don't have the same way of working or the same processing of the information.

Even if for you it seem to be problematic some people also want the user to become empty when there is no active session. These user are using this field as a "real time" connected user. It can also be interesting in a perspective where you have PC that are not specific to a user. Knowing it's not in use can also be a nice info for some of us.

Let's say we accept your request, we will most likely have a feedback that will say the contrary and told us to revert our changes.

Of course, it doesn't mean we are closed to discussion for change but I don't think changing this field's behaviour is the solution.

**Comment by bigben386** [comment]
@gillesdubois So why did those people not have to enter a feature request? There is 0 mention of this in the changelogs for the agent. We have been opening issues for the last few years and this is the first time I have seen any mention of this behavior change being made. A fundamental change like this should have been implemented via an agent option or plugin back then instead of just silently implementing it. I'm just not sure how you are even supposed to use OCS connected user as a real time user monitor as it only show 1 user for multi user systems.
