### ISSUE TITLE
ERROR *** AGENT => Failed to send Prolog <HTTP Status Code #500>

### ISSUE THREAD

**Issue by zjjollie** [OCSInventory-NG/WindowsAgent#199]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  win10 professional 64

### OCS Inventory information
Windows agent version : 2.8.0

### Problem's description
*Describe your problem here*
after installing the agent ，I can not receive the client computer info，and when I check the OCSInventory.log ，it appeared an error：

Starting OCS Inventory Agent on Wednesday, October 07, 2020 16:31:39.
AGENT => Running OCS Inventory Agent Version 2.8.0.0
AGENT => Using OCS Inventory FrameWork Version 2.8.0.0
AGENT => Loading plug-in(s)
AGENT => Using network connection with Communication Server
AGENT => Using Communication Provider <OCS Inventory cURL Communication Provider> Version <2.8.0.0>
AGENT => Sending Prolog
ERROR *** AGENT => Failed to send Prolog <HTTP Status Code #500>
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:01.

please help me out， thx

**Comment by dit-aix** [comment]
même problème ici,
l'agent 2.8 ne fonctionne pas du tout.
Un agent 2.6 fonctionne partiellement avec le serveur en 2.8 (tout sauf les logiciels dont la structure à changée dans la base)

error log: 

	INVENTORY => XML Update 31 Network Adapter(s)
	INVENTORY => XML Update 1 Video Adapter(s)
	INVENTORY => XML Update 3 Monitor(s)
	INVENTORY => XML Update 8 Printer(s)
	INVENTORY => XML Update 388 Software
	INVENTORY => XML Update 37 Registry Value(s)
	INVENTORY => XML Update Administrative Information(s)
	INVENTORY => XML Update common Device properties
	COM SERVER => Initializing cURL library for sendRequest
	COM SERVER => Using cURL without server authentication
	COM SERVER => Disabling cURL proxy support
	COM SERVER => Enabling cURL SSL server validation support using CA Bundle <cacert.pem>
	COM SERVER => Sending HTTP Post request to URL <XXXXXXXXXXXXXXXXX>
	COM SERVER => HTTP Post response received <HTTP Status Code #500>
	COM SERVER => Cleaning cURL library
ERROR *** AGENT => Failed to send Inventory <HTTP Status Code #500>
AGENT =>  Communication Server asked for Package Download
	DOWNLOAD => Package history file cleaning not required
DOWNLOAD => Download and setup tool successfully started
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:27.

**Comment by dzsajo** [comment]
I had missing columns in printer table. I marked them.

CREATE TABLE `printers` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `HARDWARE_ID` int(11) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `DRIVER` varchar(255) DEFAULT NULL,
  `PORT` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  **`SERVERNAME` varchar(255) DEFAULT NULL,
  `SHARENAME` varchar(255) DEFAULT NULL,
  `RESOLUTION` varchar(50) DEFAULT NULL,
  `COMMENT` varchar(255) DEFAULT NULL,
  `SHARED` int(11) DEFAULT NULL,
  `NETWORK` int(11) DEFAULT NULL,**
  PRIMARY KEY (`ID`),
  KEY `HARDWARE_ID` (`HARDWARE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by dit-aix** [comment]
my printer table already has servername, sharename,resolution,comment,shared and network columns :

MariaDB [ocsweb]> desc printers;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| ID          | int(11)      | NO   | PRI | NULL    | auto_increment |
| HARDWARE_ID | int(11)      | NO   | MUL | NULL    |                |
| NAME        | varchar(255) | YES  |     | NULL    |                |
| DRIVER      | varchar(255) | YES  |     | NULL    |                |
| PORT        | varchar(255) | YES  |     | NULL    |                |
| DESCRIPTION | varchar(255) | YES  |     | NULL    |                |
| SERVERNAME  | varchar(255) | YES  |     | NULL    |                |
| SHARENAME   | varchar(255) | YES  |     | NULL    |                |
| RESOLUTION  | varchar(50)  | YES  |     | NULL    |                |
| COMMENT     | varchar(255) | YES  |     | NULL    |                |
| SHARED      | int(11)      | YES  |     | NULL    |                |
| NETWORK     | int(11)      | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
12 rows in set (0.00 sec)

**Comment by gillesdubois** [comment]
Hi,

Here are a few infos on how to debug an agent 500 error : 

* Remove all plugins from the agent folder and perform an inventory. If the error doesn't happen anymore, it mean that one of your plugin is wrongly installed or have an older database model than the client addon you are using. It can be fixed easily by reinstalling the plugin completely.

* To have a better idea of what's causing the problem, edit your z-ocsinventory-server.conf, set "DBI_PRINT_ERROR" (it might not be exactly the setting name) to one and restart the service. After running an agent inventory the apache error log will have more verbosity so you can target the problem's source. It will be most likley a database insertion error. If the message seem understandable for you, fix it. Otherwise send the error in this issue.

From experience its most likely a database schema update issue. On OCS instances with a lot of assets some database update doesn't pass correctly. (It can also come from the PHP configuration).

Regards,
Gilles.

**Comment by dit-aix** [comment]
no plugins on my server.

I tried to enable DBI_PRINT_ERROR and i got 3 errors :
DBD::mysql::st execute failed: Column 'ID' in field list is ambiguous at /usr/local/share/perl5/Apache/Ocsinventory/Server/Capacities/Download.pm line 268.

DBD::mysql::st fetchrow_hashref failed: fetch() without execute() at /usr/local/share/perl5/Apache/Ocsinventory/Server/Capacities/Download.pm line 270.

DBD::mysql::db do failed: Table 'ocsweb.softwares' doesn't exist at /usr/local/share/perl5/Apache/Ocsinventory/Server/Inventory/Update.pm line 96.

I'm sure that the third error is du to client 2.4 and 2.6, because the structure and the name of the table changed in 2.8
I'm sure too that the 2 other errors are ralated to 2.4 and 2.6 agent because i have many (more than 10) lines per minute (about 10000 client in 2.4/2.6 and only 2 client in 2.8)

I can't isolate errors from 2.8 client so either there is no error in the log, either the errors are the same than 2.4/2.6 client.

**Comment by dit-aix** [comment]
for the error : 
DBD::mysql::st execute failed: Column 'ID' in field list is ambiguous at /usr/local/share/perl5/Apache/Ocsinventory/Server/Capacities/Download.pm line 268.

the query at line 268 is : 

MariaDB [ocsweb]> SELECT ID, FILEID, INFO_LOC, PACK_LOC, CERT_PATH, CERT_FILE, SERVER_ID
    ->       FROM devices,download_enable
    ->       WHERE HARDWARE_ID=91413
    ->       AND devices.IVALUE=download_enable.ID
    ->       AND devices.NAME='DOWNLOAD'
    ->       AND (TVALUE IS NULL OR TVALUE='NOTIFIED');

and it reports an error when i run it by the cli :
ERROR 1052 (23000): Column 'ID' in field list is ambiguous

i checked and both that 2 tables devices,download_enable had an ID column :
MariaDB [ocsweb]> desc devices
    -> ;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| ID          | int(11)      | NO   | PRI | NULL    | auto_increment |
| HARDWARE_ID | int(11)      | NO   | MUL | NULL    |                |
| NAME        | varchar(50)  | NO   | MUL | NULL    |                |
| IVALUE      | int(11)      | YES  | MUL | NULL    |                |
| TVALUE      | varchar(255) | YES  | MUL | NULL    |                |
| COMMENTS    | text         | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
6 rows in set (0.01 sec)

MariaDB [ocsweb]> desc download_enable;
+-----------+--------------+------+-----+---------+----------------+
| Field     | Type         | Null | Key | Default | Extra          |
+-----------+--------------+------+-----+---------+----------------+
| ID        | int(11)      | NO   | PRI | NULL    | auto_increment |
| FILEID    | varchar(255) | NO   | MUL | NULL    |                |
| INFO_LOC  | varchar(255) | NO   |     | NULL    |                |
| PACK_LOC  | varchar(255) | NO   |     | NULL    |                |
| CERT_PATH | varchar(255) | YES  |     | NULL    |                |
| CERT_FILE | varchar(255) | YES  |     | NULL    |                |
| SERVER_ID | int(11)      | YES  |     | NULL    |                |
| GROUP_ID  | int(11)      | YES  |     | NULL    |                |
+-----------+--------------+------+-----+---------+----------------+
8 rows in set (0.00 sec)

**Comment by dit-aix** [comment]
any more advice to debug client 2.8 error : COM SERVER => HTTP Post response received <HTTP Status Code #500> ?

**Comment by dit-aix** [comment]
finally, my server had several bugs :
- software table was empty after upgrade => probably a timeout during update, i had to run manually sql patches with the mysql cli (and restore softwares table from a backup)

- Perl composant of OCS was not upgraded by the web installer, the database was in 2.8, the ocsreports web site too but the perl composant was older. I had to manually run : perl Makefile.PL / make / make install in OCSNG_UNIX_SERVER_2.8\Apache
(same issue here : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/1045)

- http error log was full of "DBD::mysql::db do failed: The table 'prolog_conntrack' is full at /usr/local/share/perl5/Apache/Ocsinventory/Server/Communication/Session.pm line 46" but there planty of space left on the server, the problem was in innodb memory allocation which is limited by default in mysql . The new software* tables structure combinated with my 10.000 host exceed the default memory allocation. I had to add to my.cnf, in mysqld section : innodb_data_file_path = ibdata1:10M:autoextend

- LDAP login configuration was crush by var.php upgrade

- Mysql login parameters were crush by a file update (don't remember which one)


OCSinventory updates are always difficult but this one was the worst.

**Comment by bgoroll** [comment]
> From experience its most likely a database schema update issue.

And is there an script or option to make a clean database during the update, but keep the old collected inventories inside new database?

**Comment by charleneauger** [comment]
Hi,

Knowing that this issue concerns version 2.8 and that the current version of the server is 2.11.1 and of the agent is 2.10.1.0, I am closing this issue.

Please reopen an issue if you encounter this problem with the latest version.

Regards,
Charlene
