### ISSUE TITLE
Update from 2.6 to 2.8 - Download.exe not Updated

### ISSUE THREAD

**Issue by LMS235** [OCSInventory-NG/WindowsAgent#202]
### General information
Operating system :  Windows 10

### OCS Inventory information
Windows agent version : 2.8

### Problem's description
After the update from 2.6 to 2.8, on some clients the "Download.exe" was not also raised to 2.8. This remained at 2.6 and therefore triggered the ERR_BAD_DIGEST.

On the affected clients we had to update the downloader manually. The update itself ran as follows "OCS-Windows-Agent-Setup-x64.exe /S /UPGRADE /server=https://xxxxxxxxxxx/ocsinventory /ssl=1 /debug=0 /NO_SYSTRAY /NOW /CaBundle=cacert.pem".

On about 80% of all computers without problems, on the rest the "Download.exe" part in the agent was simply not updated.

**Comment by sokatra** [comment]
in my opinion the update process was always buggy .. so i recommend to uninstall the old client and install the new one

**Comment by LMS235** [comment]
well, but that should not be the solution. Here there should be a solution until the next release.

**Comment by charleneauger** [comment]
Hi @sokatra @LMS235 ,

Updating the Windows Agent from an OCS deployment causes a problem. This problem will be fixed in version 2.9 with an overhaul of the deployment functionality. In the meantime, we recommend that you use the deployment to send the agent setup to the machines with a script that starts the installation later.

Best regards,
Charlene Auger
