### ISSUE TITLE
Windows 8 Pro and newer WINPRODKEY does not match

### ISSUE THREAD

**Issue by gillesdubois** [OCSInventory-NG/WindowsAgent#21]
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/116

**Comment by scifire91** [comment]
@gillesdubois whats the current state of this issue? Will this be fixed?

**Comment by Ramzes50** [comment]
Sorry for my English.
The problem with the keys in Windows 8 and 10 I know how to solve, to date, tested on 15 computers. It is necessary in the source code to correct the function GetWindowsProductKey located in SysInfo/Registry.cpp
Where should I put the code so that you can fix this error in the next agent release?

**Comment by scifire91** [comment]
@Ramzes50 i think you can create a pull request with the fix or poste it in this thread.

**Comment by Ramzes50** [comment]
Added pull request.

**Comment by charleneauger** [comment]
Hi,
Your problem has been solved.
The pull request https://github.com/OCSInventory-NG/WindowsAgent/pull/41 has been merged.
@Ramzes50 : Thanks for your contribution.

Regards
Charlène
