### ISSUE TITLE
Where TAG value is Stored:

### ISSUE THREAD

**Issue by lucasdiedrich** [OCSInventory-NG/WindowsAgent#36]
Hello, i'm writing a Puppet Module to install ocsinventory on Windows 10. I would like to know where this value is store, i can't find the location.

Thank you.

**Comment by gillesdubois** [comment]
hi @lucasdiedrich ,

The TAG data is written in the agent configuration located in : %programdata%/OCS Inventory NG/
It appear as "TAG=MYTAG" in the configuration file.

Regards,
Gilles Dubois.

**Comment by lucasdiedrich** [comment]
@gillesdubois , thats the problem, the TAG value is not writed at %programdata%/OCS Inventory NG/agent/ocsinventory.ini, i'm using the 2.2.0.0 version.

**Comment by niek1992xCYSO** [comment]
Any updates on this? I've scoured the documentation on OCS Inventory Agent NG and no mentions of TAG= inside of [OCS Inventory Agent]. The example `ocsinventory.ini` is also rather old (and seems to me like it's not updated).  We're running into the same problem (using Puppet) and Windows clients.

**Comment by niek1992xCYSO** [comment]
So to get back to this; I think i've managed to "fix" this issue or at least locate the issue at hand. If the installer is at some point started without /TAG=<somevalue>, it'll hide admininfo.conf in %programdata%/OCS Inventory NG/Agent/. But the file is there, and the value is set to NA. It isn't visible in Explorer, but if you CMD into that directory and type in the filename and hit enter, you'll open the file:

![Image](https://github.com/user-attachments/assets/12d85121-4a56-4d61-8988-8a3cae9a046d)

I only found this out because i re-ran the installer, which caused the file to be unhidden (yes, i have "show hidden items" checked), with a date of when the VM was first provisioned. So i'm thinking of using a .erb file to provide the value via Puppet, with $certname. And i don't think Puppet will turn it into an issue if i'll be replacing the entire file.
