### ISSUE TITLE
OcsLogon.exe - VirusTotal detecting possible malware

### ISSUE THREAD

**Issue by daniejstriata** [OCSInventory-NG/WindowsAgent#40]
### General informations
Operating system :  Windows

### OCS Inventory informations
Windows agent version : 2.3.0
  Product: OCS Inventory NG Logon Installer
  File version: 2.2.0.0

### Problem's description
I found a file called OcsLogon.exe and scanning it with VirusTotal found possible malware / Trojan code in the binary. I'm not sure if this is accidental or not but it does make it a bit difficult to use in our environment getting this past our security team with fully understanding this.

https://www.virustotal.com/en/file/4dc949286fa5bfaee096a4b6b03d87580863a6d352b54b6b7eff1170b31be7d7/analysis/1496306827/

**Comment by kapouik** [comment]
Ah Ah, I love stupid security tools ...

Yes, OCSLogon contain a tool to download other binary package and install it in quiet mode on your computer :)
You can test wget tools on the website virustotal and you will find many virus found (wget is a tool to fetch anything on a webserver and that is install on many many linux server)

You will allways find a paranoid tool that found a virus in notepad.exe. If major antivirus found nothing : that there is nothing to find (by major antivirus I think McAfee,  Kaspersky, BitDefender, G-Data, Clamav or Norton)

**Comment by noraisk** [comment]
I recommend start adding digital signatures for publicy released executables. And please take malware detections seriously as otherwise some users could not use the product because of security policies. 

Couple of examples:
http://gizmodo.com/mac-bittorrent-client-transmission-gets-infected-with-m-1785957214
https://www.theregister.co.uk/2016/02/21/linux_mint_hacked_malwareinfected_isos_linked_from_official_site/
